//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by M_WA.rc
//
#define IDD_M_WA_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDD_DLGITEMLOG                  132
#define IDD_DLGCASHLOG                  133
#define IDD_DLGQUESTLOG                 134
#define IDD_DLGMAILLOG                  135
#define IDD_DLGUSERLOG                  136
#define IDD_DLGITEMSHOP                 137
#define IDD_DLGUSERMANAGE               138
#define IDD_DLGITEMMANAGE               139
#define IDD_DLGBANLIST                  140
#define IDD_DLGCHARLOG                  141
#define IDD_DLGRANKING                  144
#define IDD_DLGPETLOG                   145
#define IDD_DLGGUILDINFO                146
#define IDD_DLGGUILDLOG                 147
#define IDD_DLGPETMANAGE                148
#define IDD_DLGGUILDMANAGE              149
#define IDD_DLGPLAYERINFO               151
#define IDD_DLGMAILSEND                 154
#define IDC_GRPSEARCH                   1000
#define IDD_DLGUSERINFO                 1000
#define IDC_LBLSERVER                   1001
#define IDD_DLGKICKPLAYER               1001
#define IDC_CMBSERVER                   1002
#define IDD_DLGBANPLAYER                1002
#define IDC_LBLNAME                     1003
#define IDD_DLGNOTICE                   1003
#define IDC_EDITNAME                    1004
#define IDSEARCH                        1005
#define IDC_TABRESULT                   1006
#define IDC_LBLNAME2                    1006
#define IDSEARCH2                       1006
#define IDC_PROGRESSMAIL                1006
#define IDC_TABRESULT2                  1007
#define IDC_LBLMAIN                     1009
#define IDC_GRPPAGE                     1010
#define IDC_LBLPROG                     1010
#define IDC_LBLPAGE                     1011
#define IDC_CMBPAGE                     1012
#define IDD_DLGLOGINLOG                 1012
#define IDC_LISTRESULT                  1013
#define IDC_LISTUSERINFO                1015
#define IDC_LBLQUESTTYPE                1016
#define IDC_LBLQUESTTYPE2               1017
#define IDC_CMBQUESTTYPE                1018
#define IDC_CMSEARCHTYPE                1019
#define IDC_EDITACCOUNT                 1020
#define IDC_LBLACCOUNT                  1021
#define IDC_LBLBANACCOUNT               1022
#define IDC_EDITPATH                    1022
#define IDC_EDITBANACCOUNT              1023
#define IDC_LBLBANREASON                1024
#define IDC_EDITBANREASON               1025
#define IDC_BTNBAN                      1026
#define IDC_BTNRESET                    1027
#define IDC_LBBANTIME                   1028
#define IDC_LBLBANTIME                  1028
#define IDC_LBLHINT                     1029
#define IDC_GRPSERVER                   1030
#define IDC_BANTIME                     1030
#define IDC_CHECKSELECTALL              1031
#define IDC_LBBANTIME2                  1031
#define IDC_LBLBANDATE                  1031
#define IDC_LISTSERVER                  1032
#define IDC_LBLBANTYPE                  1032
#define IDC_LBLSTARTTIME                1033
#define IDC_EDITBANTYPE                 1033
#define IDC_LBLENDTIME                  1034
#define IDC_LBLHINT2                    1034
#define IDC_LBLHINTA                    1034
#define IDC_LBLINTERVAL                 1035
#define IDC_LBLCONTENT                  1036
#define IDC_DTPSTARTDATE                1037
#define IDC_DTPSTARTTIME                1038
#define IDC_DTPENDDATE                  1039
#define IDC_DTPENDTIME                  1040
#define IDC_EDITINTERVAL                1041
#define IDC_LBLTIME                     1042
#define IDC_CHECKIMME                   1043
#define IDC_LBLSECOND                   1043
#define IDC_LBLSTATUS                   1044
#define IDC_CMBSTATUS                   1045
#define IDC_EDITCONTENT                 1046
#define IDBTNNOTICE                     1047
#define IDBTNRESET                      1048
#define IDC_BTNNOTICEINFO               1049
#define IDC_BTDELETE                    1050
#define IDC_LISTNOTICE                  1051
#define IDC_EDITBANREASONCO             1051
#define IDC_EDITBANREASONCOM            1051
#define IDC_SCROLLBAR1                  1052
#define IDC_LBLLOGTYPE                  1053
#define IDC_CMBLOGTYPE                  1054
#define IDC_CHECKRECEIVER               1058
#define IDC_CHECKSENDER                 1061
#define IDC_EDITNICK                    1062
#define IDC_LBLNICK                     1063
#define IDC_CMBSKILL                    1064
#define IDC_EDITNICKNAME                1064
#define IDC_EDITITEMNUM                 1064
#define IDC_LBLOLD                      1065
#define IDC_LBLNICKNAME                 1065
#define IDC_BTNEDIT                     1066
#define IDC_LBLPETLEVEL                 1066
#define IDC_BTNRECOVER                  1067
#define IDC_LBLNEW                      1068
#define IDC_EDITNEW                     1069
#define IDC_EDITOLD                     1070
#define IDC_LBLSKILL                    1071
#define IDC_LBLPETATTR                  1071
#define IDC_LBLNUM                      1071
#define IDC_EDITSKILL                   1072
#define IDC_EDITTIME                    1072
#define IDC_LBLLEVEL                    1073
#define IDC_LBLITEM                     1073
#define IDC_EDITLEVEL                   1074
#define IDC_EDITITEM                    1074
#define IDC_BTNEDITLVL                  1075
#define IDC_BTNDELITEM                  1075
#define IDC_BTNDELSKILL                 1076
#define IDC_CMBITEM                     1076
#define IDC_BTNITEMLIST                 1077
#define IDC_LBLITEMNAME                 1078
#define IDC_BTNLOG                      1079
#define IDC_CMBQUALITY                  1079
#define IDC_LBLGUILD                    1080
#define IDC_LBLQUALITY                  1080
#define IDC_EDITGUILD                   1081
#define IDC_LBLMAILSUBJECT              1081
#define IDC_CMBRESULT                   1082
#define IDC_EDMAILSUBJECT               1082
#define IDC_CMBBASIC                    1083
#define IDC_LBLMAILCONTENT              1083
#define IDC_LISTBASIC                   1084
#define IDC_EDMAILCONTENT               1084
#define IDC_LBLPET                      1085
#define IDC_CMBPET                      1086
#define IDC_EDITPETLEVEL                1087
#define IDC_EDITPETATTR                 1088
#define IDC_LBLPETNAME                  1089
#define IDC_EDITPETNAME                 1090
#define IDC_BTNDELPET                   1091
#define IDC_LBLEDITNAME                 1092
#define IDC_LBLMODNAME                  1093
#define IDC_EDITMODNAME                 1094
#define IDC_BTNDEL                      1095
#define IDC_LBLMAILMONEY                1095
#define IDC_EDITEDITNAME                1096
#define IDC_EDMAILMONEY                 1096
#define IDC_BTNTRANSFER                 1097
#define IDC_LBLNEWVALUE                 1099
#define IDC_EDITNEWVALUE                1100
#define IDC_CHECKBATCH                  1101
#define IDC_BTNBROWSE                   1102
#define IDC_CHECKGROUP                  1103
#define IDC_LBLPATH                     1105
#define IDC_CMBTYPE                     1106
#define IDC_BTNSEND                     1106
#define IDC_CHECKBYACCOUNT              1121
#define IDC_CHECKBYIP                   1122
#define IDC_IPADDRESSCHECK              1123
#define IDC_LBLIP                       1124
#define IDC_LISTITEM                    1132
#define IDC_LBLTOADDITEM                1133
#define IDC_BTNADD                      1134
#define IDC_BTNDELETE                   1135
#define IDC_BTMULTICLOSE                1141
#define IDC_LBLSOURCE                   1144
#define IDC_BTBROWSE                    1145
#define IDC_LBLFILE                     1175
#define IDC_ETFILE                      1176
#define IDC_CMBCATEGORY                 12003
#define IDC_CMB1                        12003
#define IDC_STATICCATEGORY              12013
#define IDC_CMBACTION                   12014
#define IDC_STATICACTION                12015
#define IDC_STATICSTARTTIME             12016
#define IDC_STATICENDTIME               12017
#define IDC_DATESTART                   12018
#define IDC_TIMESTART                   12019
#define IDC_DATEEND                     12020
#define IDC_TIMEEND                     12021
#define IDC_ED1                         12133
#define IDC_ED4                         12134
#define IDC_LBL1                        12168
#define IDC_CKITEMTYPE                  12169
#define IDC_BTN1                        12170
#define IDC_CMB2                        12171
#define IDC_ED3                         12172
#define IDC_ED2                         12173
#define IDC_ED5                         12174
#define IDC_ED7                         12175
#define IDC_BTN2                        12176
#define IDC_BTN3                        12177
#define IDC_LBL2                        12178
#define IDC_LBL3                        12179
#define IDC_LBL4                        12180
#define IDC_LBL5                        12181
#define IDC_LBL6                        12182
#define IDC_GRPSEARCHN                  22000
#define IDUISEARCH                      22001
#define IDUICANCEL                      22002
#define IDC_LBLUISERVER                 22003
#define IDC_LBLUIACCOUNT                22004
#define IDC_LBLUINICK                   22005
#define IDC_CMBUISERVER                 22006
#define IDC_EDITUIACCOUNT               22007
#define IDC_EDITUINICK                  22008
#define IDC_TABUIRESULT                 22009
#define IDC_GRPUIPAGE                   22010
#define IDC_CMBUIPAGE                   22011
#define IDC_LISTUSERINFON               22012
#define IDC_LBLUIPAGE                   22013
#define IDC_LBLSELFTYPE                 22014
#define IDC_CMBSELFTYPE                 22015
#define IDD_DLGBANKMANAGE               22022
#define IDD_DLGDELITEMINFO              22026
#define IDD_DLGMAIL                     22027
#define IDD_DLGPETINFOR                 22028
#define IDD_DLGGOODSINFOR               22029
#define IDC_LISTCHARACTER               22061
#define IDC_CMBUSERPAGE                 22062

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1107
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
