//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by M_PAL.rc
//
#define IDD_DLGUSERINFO                 1000
#define IDC_GRPSEARCH                   1000
#define IDC_LBLSERVER                   1001
#define IDD_DLGKICKPLAYER               1001
#define IDC_CMBSERVER                   1002
#define IDD_DLGBANPLAYER                1002
#define IDC_LBLNAME                     1003
#define IDD_DLGNOTICE                   1003
#define IDC_EDITNAME                    1004
#define IDD_DLGGUILDMANAGE              1004
#define IDSEARCH                        1005
#define IDD_DLGROLEMANAGE               1005
#define IDC_TABRESULT                   1006
#define IDD_DLGLOGINFO                  1006
#define IDD_DLGITEMINFO                 1007
#define IDC_LBLADDNAME                  1007
#define IDD_DLGITEMMANAGE               1008
#define IDC_EDITNAME2                   1008
#define IDC_EDITADDNAME                 1008
#define IDD_DLGGUILDINFO                1009
#define IDC_GRPPAGE                     1010
#define IDD_DLGBANKINFO                 1010
#define IDC_LBLPAGE                     1011
#define IDD_DLGMAILBOXINFO              1011
#define IDC_CMBPAGE                     1012
#define IDD_DLGLOGINLOG                 1012
#define IDC_LISTRESULT                  1013
#define IDD_DLGSHOPBUYLOG               1013
#define IDD_DLGQUERYBAN                 1014
#define IDC_LISTRESULT2                 1014
#define IDC_LISTMAILDETAIL              1014
#define IDC_LBLPAGE2                    1014
#define IDC_LISTUSERINFO                1015
#define IDB_HDRDOWN                     1015
#define IDC_CMBPAGE2                    1015
#define IDC_LBLQUESTTYPE                1016
#define IDB_HDRUP                       1016
#define IDC_LBLBAGTYPE                  1017
#define IDD_DLGAUCTIONINFO              1017
#define IDC_CMBQUESTTYPE                1018
#define IDC_CMBBAGTYPE                  1019
#define IDD_DLGCDKEYITEMGET             1019
#define IDC_EDITACCOUNT                 1020
#define IDD_DLGSENDPWD                  1020
#define IDC_LBLACCOUNT                  1021
#define IDD_DLGHISLOGINFO               1021
#define IDC_LBLBANACCOUNT               1022
#define IDD_DLGMOBMANAGE                1022
#define IDC_EDITBANACCOUNT              1023
#define IDD_DLGMOBINFO                  1023
#define IDC_LBLBANREASON                1024
#define IDD_DLGPUZZLEMAPMANAGE          1024
#define IDC_EDITBANREASON               1025
#define IDD_DLGPUZZLEMAPINFO            1025
#define IDC_BTNBAN                      1026
#define IDD_DLGMOVETOSAFE               1026
#define IDC_BTNRESET                    1027
#define IDD_DLGROLEDEL                  1027
#define IDD_DLGCHARACTERINFO            1028
#define IDC_LBLHINT                     1029
#define IDD_DLGUSERINFOONLY             1029
#define IDC_GRPSERVER                   1030
#define IDD_DLGSENDCUSTOMERITEM         1030
#define IDC_CHECKSELECTALL              1031
#define IDC_LISTSERVER                  1032
#define IDC_LBLSTARTTIME                1033
#define IDC_LBLENDTIME                  1034
#define IDC_LBLINTERVAL                 1035
#define IDC_LBLCONTENT                  1036
#define IDC_DTPSTARTDATE                1037
#define IDC_DTPSTARTTIME                1038
#define IDC_DTPENDDATE                  1039
#define IDC_DTPENDTIME                  1040
#define IDC_EDITINTERVAL                1041
#define IDC_LBLTIME                     1042
#define IDC_CHECKIMME                   1043
#define IDC_LBLSTATUS                   1044
#define IDC_CMBSTATUS                   1045
#define IDC_EDITCONTENT                 1046
#define IDBTNNOTICE                     1047
#define IDBTNRESET                      1048
#define IDC_BTNNOTICEINFO               1049
#define IDC_LISTNOTICE                  1051
#define IDC_LBLGUILD                    1052
#define IDC_EDITGUILD                   1053
#define IDC_LISTGUILD                   1056
#define IDC_LBLGUILDNAME                1057
#define IDC_EDITGUILDNAME               1058
#define IDC_LBLNEWGUILDNAME             1059
#define IDC_EDITNEW                     1060
#define IDC_LBLGUILDLVL                 1061
#define IDC_CMBGUILDLVL                 1062
#define IDC_LBLREASON                   1063
#define IDC_EDITREASON                  1064
#define IDC_LBLMEMBERLVL                1065
#define IDC_LISTMEMBER                  1066
#define IDC_BTNMODI                     1067
#define IDC_CMBMEMBERLVL                1068
#define IDC_LBLBIGTYPE                  1069
#define IDC_LBLMEMBERREASON             1069
#define IDC_LBLSMALLTYPE                1070
#define IDC_EDITMEMBERREASON            1070
#define IDC_CMBBIGTYPE                  1071
#define IDC_CMBSMALLTYPE                1072
#define IDC_BTNSEARCHLOG                1075
#define IDC_LBLMAILSUBJECT              1076
#define IDC_EDMAILSUBJECT               1077
#define IDC_LBLMAILCONTENT              1078
#define IDC_EDMAILCONTENT               1079
#define IDC_LBLMAILMONEY                1095
#define IDC_EDMAILMONEY                 1096
#define IDC_BTNSEND                     1097
#define IDC_LBLMAILREASON               1099
#define IDC_EDMAILREASON                1100
#define IDC_LBLSRC                      1101
#define IDC_LBLNEW                      1102
#define IDC_EDITSRC                     1103
#define IDC_LBLTYPE                     1105
#define IDC_CMBTYPE                     1106
#define IDC_LBLQUESTNAME                1109
#define IDC_EDITQUESTNAME               1110
#define IDC_LBLQUESTSTATUS              1111
#define IDC_CMBQUESTSTATUS              1112
#define IDC_BTNMODIQUEST                1113
#define IDC_LBLROLENAME                 1114
#define IDC_EDITROLENAME                1115
#define IDC_EDITNMONEY                  1116
#define IDC_EDITSMONEY                  1117
#define IDC_LBLMEMBERNAME               1118
#define IDC_EDITMEMBERNAME              1119
#define IDC_BTNMODIMEMBERLVL            1120
#define IDC_CHECKBYACCOUNT              1121
#define IDC_CHECKBYIP                   1122
#define IDC_IPADDRESSCHECK              1123
#define IDC_LBLIP                       1124
#define IDC_CHECKBUY                    1125
#define IDC_CHECKSEND                   1126
#define IDC_LBLITEMNUM                  1130
#define IDC_EDITITEMNUM                 1131
#define IDC_LISTITEM                    1132
#define IDC_LBLTOADDITEM                1133
#define IDC_BTNADD                      1134
#define IDC_BTNDELETE                   1135
#define IDC_LBLUSERNAME                 1136
#define IDC_EDITUSERNAME                1137
#define IDC_LBLMAILBOX                  1138
#define IDC_EDITMAILBOX                 1139
#define IDC_BTNSENDMAIL                 1140
#define IDC_BUTTON2                     1141
#define IDC_BTN2                        1141
#define IDC_BTMULTICLOSE                1141
#define IDC_LBLSOURCE                   1144
#define IDC_BUTTON1                     1145
#define IDC_BTNGETEMAIL                 1145
#define IDC_BTN1                        1145
#define IDC_BTBROWSE                    1145
#define IDC_BTQUEIRYITEM                1145
#define IDC_EDROLENAME                  1147
#define IDC_CBZONENAME                  1148
#define IDC_LBL1                        1149
#define IDC_LBL2                        1150
#define IDC_LBL0                        1153
#define IDC_LBL3                        1154
#define IDC_LBL4                        1155
#define IDC_LBL5                        1156
#define IDC_LBL6                        1157
#define IDC_LBL7                        1158
#define IDC_LBL8                        1159
#define IDC_LBL9                        1160
#define IDC_PUZZLEMAP                   1161
#define IDC_CB1                         1162
#define IDC_CB2                         1163
#define IDC_CB3                         1164
#define IDC_CB4                         1165
#define IDC_CB5                         1166
#define IDC_CB6                         1167
#define IDC_CB7                         1168
#define IDC_CB8                         1169
#define IDC_CB9                         1170
#define IDC_MONTHCALENDAR1              1171
#define IDC_LBLFILE                     1175
#define IDC_ETFILE                      1176
#define IDC_LIST1                       1182
#define IDC_CITYALL                     1183
#define IDC_CHEAK_CITYALL               1183
#define IDC_STATICSUBJECT               1189
#define IDC_STATICCONTENT               1190
#define IDC_STATICMONEY                 1191
#define IDC_STATICITEMNAME              1192
#define IDC_STATICSTATUS                1193
#define IDC_CHECKBIND                   1194
#define IDC_CHECKNOTBIND                1195
#define IDC_STATICREASON                1196
#define IDC_ETSUBJECT                   1197
#define IDC_ETCONTENT                   1198
#define IDC_ETMONEY                     1199
#define IDC_CMBITEMNAME                 1200
#define IDC_ETSENDREASON                1201
#define IDC_CHECKSTONE                  1202
#define IDC_STATICSTONE0                1203
#define IDC_STATICSTONE1                1204
#define IDC_STATICSTONE2                1205
#define IDC_STATICSTONE3                1206
#define IDC_STATICSTONE4                1207
#define IDC_STATICSTONE5                1208
#define IDC_STATICSTONE6                1209
#define IDC_STATICSTONE7                1210
#define IDC_STATICSTONE8                1211
#define IDC_STATICSTONE9                1212
#define IDC_ETSTONE9                    1213
#define IDC_ETSTONE1                    1214
#define IDC_ETSTONE2                    1215
#define IDC_ETSTONE3                    1216
#define IDC_ETSTONE4                    1217
#define IDC_ETSTONE5                    1218
#define IDC_ETSTONE6                    1219
#define IDC_ETSTONE7                    1220
#define IDC_ETSTONE8                    1221
#define IDC_ETSTONE0                    1222
#define IDC_STATICITEM                  1224
#define IDC_ETITEM                      1225

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1029
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1184
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
