//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by M_GTOWN.rc
//
#define IDC_LBLADDNAME                  1007
#define IDC_EDITADDNAME                 1008
#define IDC_LBLITEM                     1069
#define IDC_LBLITEM2                    1070
#define IDC_LBLMAILSUBJECT              1076
#define IDC_EDMAILSUBJECT               1077
#define IDC_LBLMAILCONTENT              1078
#define IDC_EDMAILCONTENT               1079
#define IDC_BTNSEND                     1097
#define IDC_LBLITEMNUM                  1130
#define IDC_EDITITEMNUM                 1131
#define IDC_LISTITEM                    1132
#define IDC_LBLTOADDITEM                1133
#define IDC_BTNADD                      1134
#define IDC_BTNDELETE                   1135
#define IDC_COMFIRM                     3018
#define IDC_BROWSE                      3019
#define IDC_FILENAME                    3020
#define IDD_DLGUSERINFO                 7000
#define IDC_GRPSEARCH                   7000
#define IDC_LBLSERVER                   7001
#define IDD_DLGBANPLAYER                7001
#define IDC_LBLACCOUNT                  7002
#define IDD_DLGNOTICE                   7002
#define IDC_LBLNAME                     7003
#define IDD_DLGKICKPLAYER               7003
#define IDC_CMBSERVER                   7004
#define IDD_DLGFAMILYINFO               7004
#define IDC_EDITACCOUNT                 7005
#define IDC_EDITNAME                    7006
#define IDSEARCH                        7007
#define IDD_DLGITEMINFO                 7008
#define IDC_LBLNICK                     7008
#define IDC_QUERY                       7008
#define IDC_TABRESULT                   7009
#define IDD_DLGITEMMANAGER              7009
#define IDD_DLGITEMMANAGE               7009
#define IDC_EDITNICK                    7009
#define IDC_GRPPAGE                     7010
#define IDD_DLGLOGINFO                  7010
#define IDC_LBLPAGE                     7011
#define IDD_DLGMAILINFO                 7011
#define IDC_CMBPAGE                     7012
#define IDD_DLGPETINFO                  7012
#define IDC_LISTUSERINFO                7013
#define IDD_DLGRELATIONSHIPINFO         7013
#define IDC_LISTRESULT                  7014
#define IDD_DLGROOMINFO                 7014
#define IDD_DLGTREASUREBOXINFO          7015
#define IDC_LBLPAGE2                    7015
#define IDD_DLGITEMCONSUME              7016
#define IDD_DLGROLEMANAGE               7017
#define IDC_LBLHINT                     7020
#define IDD_DLGTRANSMIT                 7020
#define IDD_DLGPICTUREMANAGE            7021
#define IDD_DLGQUEUEINFO                7022
#define IDD_DLGFRIENDTRADE              7023
#define IDC_LBLBANACCOUNT               7024
#define IDD_DLGBANLIST                  7024
#define IDC_EDITBANACCOUNT              7025
#define IDD_DLGUSERINFOPART             7025
#define IDC_LBLBANREASON                7026
#define IDD_DLGROLEMANAGEPART           7026
#define IDC_EDITBANREASON               7027
#define IDC_BTNBAN                      7029
#define IDC_BTNRESET                    7030
#define IDC_CHECKSELECTALL              7031
#define IDC_LISTSERVER                  7032
#define IDC_LBLSTARTTIME                7033
#define IDC_LBLENDTIME                  7034
#define IDC_DTPSTARTDATE                7035
#define IDC_DTPENDDATE                  7036
#define IDC_DTPSTARTTIME                7037
#define IDC_LBLSTARTTIME2               7037
#define IDC_DTPENDTIME                  7038
#define IDC_LBLENDTIME2                 7038
#define IDC_CHECKIMME                   7039
#define IDC_DTPSTARTDATE2               7039
#define IDC_LBLSTATUS                   7040
#define IDC_DTPENDDATE2                 7040
#define IDC_CMBSTATUS                   7041
#define IDC_LBLINTERVAL                 7042
#define IDC_EDITINTERVAL                7043
#define IDC_LBLTIME                     7044
#define IDC_LBLCONTENT                  7045
#define IDC_EDITCONTENT                 7046
#define IDBTNNOTICE                     7047
#define IDBTNRESET                      7048
#define IDC_BTNNOTICEINFO               7049
#define IDC_LISTNOTICE                  7051
#define IDC_LISTBASIC                   7067
#define IDC_LISTMEMBER                  7067
#define IDC_LIST2                       7095
#define IDC_LBLLOGTYPE                  7098
#define IDC_CMBLOGTYPE                  7099
#define IDC_CMBUPAGE                    7101
#define IDC_LISTFAMILY                  7108
#define IDC_LBLFAMILY                   7109
#define IDC_CMBFPAGE                    7110
#define IDC_EDITFAMILY                  7111
#define IDC_CMBTYPE                     7113
#define IDC_LBLTYPE                     7114
#define IDC_EDITITEM                    7115
#define IDC_LBLTYPE2                    7115
#define IDC_CMBUSER                     7116
#define IDC_BTNBLURSEARCH               7117
#define IDC_BTNMOVEUUSER                7118
#define IDC_BTNRESETSTATUS              7119
#define IDC_BUTTON3                     7120
#define IDC_BTNCLEARNAME                7120
#define IDC_CMBUIPAGE                   7121
#define IDC_EDITX                       7122
#define IDC_LBLX                        7123
#define IDC_EDITY                       7124
#define IDC_LBLY                        7125
#define IDC_EDITZ                       7126
#define IDC_LBLZ                        7127
#define IDC_BTNTRANSMIT                 7128
#define IDC_EDITTITLE                   7129
#define IDC_LBLITEMNAME                 7130
#define IDC_ITEMNAME                    7131
#define IDC_COMBO1                      7132
#define IDC_COMBO2                      7133
#define IDUICANCEL                      22002
#define IDC_LBLUISERVER                 22003
#define IDC_CMBUISERVER                 22006
#define IDD_DLGIMPORT                   22026
#define IDD_DLGITEMCONSUME1             22027
#define IDD_DLGBACKMONEY                22027

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        7018
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         7133
#define _APS_NEXT_SYMED_VALUE           7000
#endif
#endif
