//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by M_XD.rc
//
#define IDC_BTNSEARCH                   3
#define IDD_DLGUSERINFO                 1000
#define IDC_GRPSEARCH                   1000
#define IDC_LBLSERVER                   1001
#define IDD_DLGKICKPLAYER               1001
#define IDC_CMBSERVER                   1002
#define IDD_DLGBANPLAYER                1002
#define IDC_LBLNAME                     1003
#define IDD_DLGNOTICE                   1003
#define IDC_EDITNAME                    1004
#define IDSEARCH                        1005
#define IDC_TABRESULT                   1006
#define IDC_LBLNAME2                    1006
#define IDC_PROGRESSMAIL                1006
#define IDC_LBLADDNAME                  1007
#define IDC_EDITNAME2                   1008
#define IDC_EDITADDNAME                 1008
#define IDC_LBLMAIN                     1009
#define IDC_GRPPAGE                     1010
#define IDC_LBLPROG                     1010
#define IDC_LBLPAGE                     1011
#define IDC_CMBPAGE                     1012
#define IDC_LISTRESULT                  1013
#define IDC_LISTRESULT2                 1014
#define IDC_LISTMAILDETAIL              1014
#define IDC_LBLPAGE2                    1014
#define IDC_LISTDETAIL                  1014
#define IDC_LISTUSERINFO                1015
#define IDB_HDRDOWN                     1015
#define IDC_CMBPAGE2                    1015
#define IDC_LBLQUESTTYPE                1016
#define IDB_HDRUP                       1016
#define IDC_LBLBAGTYPE                  1017
#define IDC_LBLQUESTTYPE2               1017
#define IDC_LBLSEARCHTYPE               1017
#define IDC_CMBQUESTTYPE                1018
#define IDC_CMBBAGTYPE                  1019
#define IDC_CMSEARCHTYPE                1019
#define IDC_EDITACCOUNT                 1020
#define IDC_LBLACCOUNT                  1021
#define IDC_LBLBANACCOUNT               1022
#define IDC_EDITPATH                    1022
#define IDC_EDITBANACCOUNT              1023
#define IDC_LBLSENDER                   1023
#define IDC_LBLBANREASON                1024
#define IDC_EDITSENDER                  1024
#define IDC_EDITBANREASON               1025
#define IDC_BTNBAN                      1026
#define IDC_BTNRESET                    1027
#define IDC_LBBANTIME                   1028
#define IDC_LBLHINT                     1029
#define IDD_DLGUSERMANAGE               1029
#define IDC_GRPSERVER                   1030
#define IDC_BANTIME                     1030
#define IDD_DLGITEMMANAGE               1030
#define IDC_CHECKSELECTALL              1031
#define IDC_LBBANTIME2                  1031
#define IDD_DLGITEMINFO                 1031
#define IDC_LISTSERVER                  1032
#define IDC_LBLBANTYPE                  1032
#define IDD_DLGMAILINFO                 1032
#define IDC_LBLSTARTTIME                1033
#define IDD_DLGAUCTIONINFO              1033
#define IDC_LBLSACCOUNT                 1033
#define IDC_LBLENDTIME                  1034
#define IDD_DLGITEMLOG                  1034
#define IDC_EDITSACCOUNT                1034
#define IDC_LBLINTERVAL                 1035
#define IDD_DLGMAILLOG                  1035
#define IDC_LBLCONTENT                  1036
#define IDD_DLGMCASHLOG                 1036
#define IDC_DTPSTARTDATE                1037
#define IDD_DLGCHARLOG                  1037
#define IDC_DTPSTARTTIME                1038
#define IDD_DLGLOGINLOG                 1038
#define IDC_DTPENDDATE                  1039
#define IDD_DLGITEMSHOP                 1039
#define IDC_DTPENDTIME                  1040
#define IDD_DLGGUILDINFO                1040
#define IDC_EDITINTERVAL                1041
#define IDD_DLGQUESTINFO                1041
#define IDC_LBLTIME                     1042
#define IDD_DLGCARDETAIL                1042
#define IDC_CHECKIMME                   1043
#define IDD_DLGUSERGUILD                1043
#define IDC_LBLSTATUS                   1044
#define IDD_DLGGUILDLOG                 1044
#define IDC_CMBSTATUS                   1045
#define IDD_DLGGETNPCITEM               1045
#define IDC_EDITCONTENT                 1046
#define IDD_DLGBANLIST                  1046
#define IDBTNNOTICE                     1047
#define IDD_DLGGUILDMANAGE              1047
#define IDBTNRESET                      1048
#define IDD_DLGGMMANAGE                 1048
#define IDC_BTNNOTICEINFO               1049
#define IDBDELETE                       1050
#define IDC_BTDELETE                    1050
#define IDC_LISTNOTICE                  1051
#define IDC_CMBBANTYPE                  1051
#define IDC_LBLGUILD                    1052
#define IDC_EDITGUILD                   1053
#define IDC_LBLLOGTYPE                  1053
#define IDC_CMBLOGTYPE                  1054
#define IDC_LISTGUILD                   1056
#define IDC_LBLGUILDNAME                1057
#define IDC_EDITGUILDNAME               1058
#define IDC_CHECKRECEIVER               1058
#define IDC_LBLNEWGUILDNAME             1059
#define IDC_EDITNEW                     1060
#define IDC_LBLGUILDLVL                 1061
#define IDC_CHECKSENDER                 1061
#define IDC_CMBGUILDLVL                 1062
#define IDC_EDITNICK                    1062
#define IDC_LBLREASON                   1063
#define IDC_LBLNICK                     1063
#define IDC_EDITREASON                  1064
#define IDC_CMBSKILL                    1064
#define IDC_LBLMEMBERLVL                1065
#define IDC_LBLOLD                      1065
#define IDC_LISTMEMBER                  1066
#define IDC_BTNMODI                     1067
#define IDC_CMBMEMBERLVL                1068
#define IDC_BTNEDIT                     1068
#define IDC_LBLBIGTYPE                  1069
#define IDC_LBLMEMBERREASON             1069
#define IDC_BTNRECOVER                  1069
#define IDC_LBLSMALLTYPE                1070
#define IDC_EDITMEMBERREASON            1070
#define IDC_EDITOLD                     1070
#define IDC_CMBBIGTYPE                  1071
#define IDC_LBLNUM                      1071
#define IDC_LBLSKILL                    1071
#define IDC_CMBSMALLTYPE                1072
#define IDC_EDITSKILL                   1072
#define IDC_LBLDELNUM                   1072
#define IDC_LBLITEM                     1073
#define IDC_LBLLEVEL                    1073
#define IDC_EDITITEM                    1074
#define IDC_EDITLEVEL                   1074
#define IDC_BTNSEARCHLOG                1075
#define IDC_BTNDELITEM                  1075
#define IDC_BTNEDITLVL                  1075
#define IDC_LBLMAILSUBJECT              1076
#define IDC_CMBITEM                     1076
#define IDC_BTNDELSKILL                 1076
#define IDC_EDMAILSUBJECT               1077
#define IDC_BTNITEMLIST                 1077
#define IDC_LBLMAILCONTENT              1078
#define IDC_LBLITEMNAME                 1078
#define IDC_EDMAILCONTENT               1079
#define IDC_BTNLOG                      1079
#define IDC_LBLATTRID                   1079
#define IDC_LBLATTRVALUE                1080
#define IDC_LBLMAILSUBJECT2             1081
#define IDC_CMBRESULT                   1082
#define IDC_EDMAILSUBJECT2              1082
#define IDC_CMBBASIC                    1083
#define IDC_LBLMAILCONTENT2             1083
#define IDC_LISTBASIC                   1084
#define IDC_EDMAILCONTENT2              1084
#define IDC_CMBDETAIL                   1085
#define IDC_LBLADDLEVEL                 1085
#define IDC_LBLADDTYPE                  1086
#define IDC_LBLADDVALUE                 1087
#define IDC_LBLADDVALUELAST             1088
#define IDC_LBLSTAR                     1089
#define IDC_LBLPLUGIN                   1090
#define IDC_LBLSLOTNUM                  1091
#define IDC_LBLSLOT1                    1092
#define IDC_LBLEDITNAME                 1092
#define IDC_LBLSLOT2                    1093
#define IDC_LBLMODNAME                  1093
#define IDC_LBLSLOT3                    1094
#define IDC_EDITMODNAME                 1094
#define IDC_LBLMAILMONEY                1095
#define IDC_BTNDEL                      1095
#define IDC_EDMAILMONEY                 1096
#define IDC_EDITEDITNAME                1096
#define IDC_BTNSEND                     1097
#define IDC_LBLAPTITUDE                 1097
#define IDC_LBLBIND                     1098
#define IDC_LBLMAILREASON               1099
#define IDC_CMBQUALITY                  1099
#define IDC_LBLNEWVALUE                 1099
#define IDC_EDMAILREASON                1100
#define IDC_LBLQUALITY                  1100
#define IDC_EDITNEWVALUE                1100
#define IDC_LBLSRC                      1101
#define IDC_CHECKBATCH                  1101
#define IDC_LBLNEW                      1102
#define IDC_EDITSRC                     1103
#define IDC_BTNBROWSE                   1103
#define IDC_CHECKGROUP                  1104
#define IDC_LBLTYPE                     1105
#define IDC_CMBTYPE                     1106
#define IDC_LBLQUESTNAME                1109
#define IDC_EDITQUESTNAME               1110
#define IDC_LBLQUESTSTATUS              1111
#define IDC_CMBQUESTSTATUS              1112
#define IDC_BTNMODIQUEST                1113
#define IDC_LBLROLENAME                 1114
#define IDC_EDITROLENAME                1115
#define IDC_EDITNMONEY                  1116
#define IDC_EDITSMONEY                  1117
#define IDC_LBLMEMBERNAME               1118
#define IDC_EDITMEMBERNAME              1119
#define IDC_BTNMODIMEMBERLVL            1120
#define IDC_CHECKBYACCOUNT              1121
#define IDC_CHECKBYIP                   1122
#define IDC_IPADDRESSCHECK              1123
#define IDC_LBLIP                       1124
#define IDC_CHECKBUY                    1125
#define IDC_CHECKSEND                   1126
#define IDC_LBLITEMNUM                  1130
#define IDC_EDITITEMNUM                 1131
#define IDC_LISTITEM                    1132
#define IDC_LBLTOADDITEM                1133
#define IDC_BTNADD                      1134
#define IDC_BTNDELETE                   1135
#define IDC_LBLUSERNAME                 1136
#define IDC_EDITDELNUM                  1136
#define IDC_EDITUSERNAME                1137
#define IDC_EDITATTRID                  1137
#define IDC_LBLMAILBOX                  1138
#define IDC_EDITATTRVALUE               1138
#define IDC_EDITMAILBOX                 1139
#define IDC_EDITADDLEVEL                1139
#define IDC_BTNSENDMAIL                 1140
#define IDC_EDITADDTYPE                 1140
#define IDC_BUTTON2                     1141
#define IDC_BTN2                        1141
#define IDC_BTMULTICLOSE                1141
#define IDC_EDITADDVALUE                1141
#define IDC_EDITADDVALUELAST            1142
#define IDC_EDITSTAR                    1143
#define IDC_LBLSOURCE                   1144
#define IDC_EDITPLUGIN                  1144
#define IDC_BUTTON1                     1145
#define IDC_BTNGETEMAIL                 1145
#define IDC_BTN1                        1145
#define IDC_BTBROWSE                    1145
#define IDC_EDITSLOTNUM                 1145
#define IDC_EDITSLOT1                   1146
#define IDC_EDROLENAME                  1147
#define IDC_EDITSLOT2                   1147
#define IDC_CBZONENAME                  1148
#define IDC_EDITSLOT3                   1148
#define IDC_LBL1                        1149
#define IDC_EDITAPTITUDE                1149
#define IDC_LBL2                        1150
#define IDC_EDITBIND                    1150
#define IDC_LBL0                        1153
#define IDC_LBL3                        1154
#define IDC_LBL4                        1155
#define IDC_LBL5                        1156
#define IDC_LBL6                        1157
#define IDC_LBL7                        1158
#define IDC_LBL8                        1159
#define IDC_LBL9                        1160
#define IDC_PUZZLEMAP                   1161
#define IDC_CB1                         1162
#define IDC_CB2                         1163
#define IDC_CB3                         1164
#define IDC_CB4                         1165
#define IDC_CB5                         1166
#define IDC_CB6                         1167
#define IDC_CB7                         1168
#define IDC_CB8                         1169
#define IDC_CB9                         1170
#define IDC_MONTHCALENDAR1              1171
#define IDC_LBLFILE                     1175
#define IDC_ETFILE                      1176
#define IDC_LIST1                       1182
#define IDC_LBLGMNAME                   1184
#define IDC_LBLCOORDINATE               1185
#define IDC_EDITX                       1186
#define IDC_LBLX                        1187
#define IDC_EDITY                       1188
#define IDC_LBLY                        1189
#define IDC_EDITZ                       1190
#define IDC_LBLZ                        1191
#define IDC_EDITGMNAME                  1192
#define IDC_CMBLIST                     1193
#define IDC_DATESTART                   12018
#define IDC_DATEEND                     12020
#define IDUISEARCH                      22001
#define IDUICANCEL                      22002
#define IDC_LBLUISERVER                 22003
#define IDC_LBLUIACCOUNT                22004
#define IDC_LBLUINICK                   22005
#define IDC_CMBUISERVER                 22006
#define IDC_EDITUIACCOUNT               22007
#define IDC_EDITUINICK                  22008
#define IDC_TABUIRESULT                 22009
#define IDC_GRPUIPAGE                   22010
#define IDC_CMBUIPAGE                   22011
#define IDC_LBLUIPAGE                   22013
#define IDC_LISTCHARACTER               22061
#define IDC_CMBUSERPAGE                 22062

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1049
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1194
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
